name = "uganda-family-tours"
type = "javascript"
functions = "functions"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[functions]]
name = "api/send-email"
path = "functions/api/send-email.js"
platform = "nodejs"
